### ISSUE TITLE
referrerShares and  currentWiseDay are logged in the wrong order

### ISSUE THREAD

**Issue by pauliax** [wise-foundation/wise-token-contracts#2]
https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/Events.sol#L53-L54

https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/Global.sol#L81-L82

**Comment by vm06007** [comment]
they would be reported in wrong order, but when catching this data on UI (getPastEvents()) we can swap the values before displaying on UI, not worth redeploying because of this, but thanks for spotting this so we know which value to display if we will need to.

**Comment by pauliax** [comment]
Yep, this only affects the frontend.

**Comment by vm06007** [comment]
issue addressed: https://github.com/wise-foundation/wise-token/commit/ee0b9f0c5fc34a9fd5e0a0e1c21a850159b1d380

@pauliax please leave your wallet address here in the comment for contributions and close the issue

**Comment by pauliax** [comment]
0x523B5b2Cc58A818667C22c862930B141f85d49DD

**Comment by vm06007** [comment]
sent: https://etherscan.io/tx/0x23c4d6970776392a8a552e493f4a749f09a3eba0932665ab5312a885a89f969f
