### ISSUE TITLE
NewSharePrice event is never emitted

### ISSUE THREAD

**Issue by 4thehex** [wise-foundation/wise-token-contracts#23]
`NewSharePrice` would be a useful event to emit, so that historical share price tracking/charting is much easier.  I'd also suggest maybe the event could include both the previous and new share prices?  That way the event contains info about the size of the increase.

https://github.com/wise-foundation/wise-token-contracts/blob/08a9c55a8da27699ec01f3e8e4af5e9e943f3250/contracts/Events.sol#L57-L60

I also noticed that the `NewGlobals` event would sort of cover this use case, but it's emitted via `endStake()` -> `_decreaseGlobals()` which happens before the potential share price increase in `_sharePriceUpdate()`.

**Comment by vm06007** [comment]
@4thehex please check if this is addressed in latest release: https://ropsten.etherscan.io/address/0xa89cb3aa23f7d85def5dccdb73450ae236afee61#code

**Comment by 4thehex** [comment]
> @4thehex please check if this is addressed in latest release: https://ropsten.etherscan.io/address/0xa89cb3aa23f7d85def5dccdb73450ae236afee61#code

Seems good to me!  Thank you!
