### ISSUE TITLE
Staker can scrape interest in small chunks to avoid raising the share price appropriately

### ISSUE THREAD

**Issue by 4thehex** [wise-foundation/wise-token-contracts#24]
It seems like a staker with a large stake could avoid increasing the share price by simply waiting until maturity, and then scrape all interest but via several small scrape calls, thus not raising the share price like it should if they had simply ended the stake and got all of the stake's interest at once (much larger potential share price increase).

https://github.com/wise-foundation/wise-token-contracts/blob/fe975b5f065d020ab3af065679f5c7bb738e1d1a/contracts/StakingToken.sol#L302-L358

**Comment by vm06007** [comment]
@4thehex please check if this is addressed in latest release: https://ropsten.etherscan.io/address/0xa89cb3aa23f7d85def5dccdb73450ae236afee61#code

**Comment by 4thehex** [comment]
Right on, thank you!

**Comment by vm06007** [comment]
@4thehex please leave your ethereum address

**Comment by 4thehex** [comment]
> @4thehex please leave your ethereum address

`0x5148E04B2E7A3A5f69304cebC3Be6ba6278E3923`

**Comment by 4thehex** [comment]
Havent received anything for this one FYI

**Comment by vm06007** [comment]
@4thehex sorry for the delay, we will process this payout as soon as we are done with some other stuff + gasRefunds. Thank you for your patience!

**Comment by vm06007** [comment]
https://etherscan.io/tx/0x5cc9e896c2c8e306c34e176352d789d6d4d8306b33809d367fed8d2df9c9ac0c
