### ISSUE TITLE
raising the required minium for each reservation

### ISSUE THREAD

**Issue by Alx34** [wise-foundation/wise-token-contracts#6]
https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/StakingToken.sol#L24

For each time I make a reservation for WISE token with USDC, the minimum required to deposit is raised each time. This requires me to take more USDC out of my metamask wallet each time.

**Comment by vm06007** [comment]
the amount of USDC required depends on the rate of USDC/ETH, so if ETH is rising in price it will require more USDC (as the minimum in contract is set to `0.05 ETH per day`) same is true should the ETH price start to decrease compared to USDC (it will require less USDC for single reservation then). This is normal and should be obvious. Please close the issue.
