### ISSUE TITLE
Typo in: function changePayoutPercent

### ISSUE THREAD

**Issue by ble4h** [wise-foundation/wise-token-contracts#8]
https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/RefundSponsor.sol#L50-L56

Not critical though.

**Comment by vm06007** [comment]
this contract is outside of scope, since RefundSponsor is not to be re-deployed, not something team was not aware of, but thanks for checking it out!
