### ISSUE TITLE
A possibility to artificially increase the DAI equivalent

### ISSUE THREAD

**Issue by pauliax** [wise-foundation/wise-token-contracts#9]
https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/StakingToken.sol#L138-L151

https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/ReferralToken.sol#L103-L109

I think there is a possibility to wrap this in a sandwich with such a scenario:
Create a smart contract that does a sequence of actions in one tx. First, it sends enough WETH to the WISE/WETH pair contract to temporarily increase the price of WISE. Then it creates a new stake with a referrer address. Every time the stake is created, _updateDaiEquivalent() is invoked, and _newStake.daiEquivalent is set to whatever the value is returned. With the artificially increased DAI equivalent, the referer gets a bigger increase in CM totalAmount and can easily reach the THRESHOLD_LIMIT and get an activation day. The last step is to remove the tokens from liquidity that were sent in the beginning thus returning the rate to the initial levels before the tx.
All of these steps are done in one tx thus the attacker does not risk anything. The check that the caller is not a contract is done only on referrer address, so staker can be anything. Of course, first, he needs to have a significant amount of input tokens to increase the rate on Uniswap to the levels that guarantee him to reach the THRESHOLD_LIMIT ($10,000 DAI). It is possible to use the flashloan in case the attacker does not have enough initial funds to increase the rate temporarily.

I don't know if you see this as an issue or you are aware of it but don't give it a huge priority, so it would be nice to hear your opinion on this kind of manipulation.

**Comment by pauliax** [comment]
Not sure if this is possible in a real scenario as Uniswap v2 stores cumulative price on chain from the previous block: https://uniswap.org/docs/v2/core-concepts/oracles/

**Comment by pauliax** [comment]
I am not sure if this would work in a real scenario. The Uniswap router v2 is checking the reserve value, not the token balance. The reserve value wouldn't change if you just send tokens to the pair without syncing but if you sync the reserves you can't get the tokens back out. And minting with the wrong ratios just gives you the number of liquidity tokens of whichever amount you sent less of like when you add liquidity you are supposed to send an equal amount of each asset, if you send an unequal amount and you aren't checking for it I think the pair contract just mints you LP tokens according to the lesser amount, so if you send 0 of one token it doesn't work. Maybe it could still be possible if you first buy a huge amount of WISE and at the end sell it, need to think about that more.

**Comment by vm06007** [comment]
we went over this quite a lot with CoinFabrik, these scenarios are debatable the best that could be proposed is moving average of the price for DAI perhaps when the DAI equivalent is used, but again this is still highly unlikely to impact if anything on current scales. Thanks for bringing this up though. On more thing, if you close the stake same transaction/same day, your CM referral status gets revoked - thats to make sure a person is already committed with the stake.
